os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC=gcc-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CC=g++-6; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm; fi'
  - npm -v
script:
  - 'npm run test:package'
  - 'npm run build'
  - 'npm run test:unit'
  - 'export DEBUG=testing:*'
# As the adapter requires a running Ventcube server in the local network, it does not make sense to run integration tests.
# Startup will fail, as the server is simply not reachable in Travis-CI env.
# - 'npm run test:integration'